---
- name: baitap
  hosts: all
  gather_facts: no

  tasks:
	- name: Create Vlan
  	ios_lan:
    	vlan_id: "{{ item.number }}"
      name: "{{ item.name }}"
      name: loopback 1
      ipv4: 10.0.2.1/24
      state: present
    with_items:
    	- { number: 50, name: "phong 50" }
      - { number: 51, name: "phong 51" }
      - { number: 52, name: "phong 52" }
      
   